### ISSUE TITLE
Test parameter bug.

### ISSUE THREAD

**Issue by tarce** [chenshenlv/SoundLab#1]
Error:
Not all azimuths/hrtfs are necessarily tested.  This leads to output data that can't be compared.  

To replicate:
The issue can be seen if you open subject 1's mat file and sort by hrtf and then azimuth tested.  Azimuths are not tested the same number of times for each HRTF.  

Proposed Solution:
The issue is that the two arrays at line 232 and 234 are created separately and randomized separately.  The selection makes it so that a random HRTF and azimuth are chosen but there is no check to ensure that the same number of tests have been done for each HRTF at each azimuth.  A simple solution is to create pairs of HRTF,Az and randomize these instead of treating them separately.

Extra:
We will not use the data collected thus far until this error is taken care of.  Once corrected please create test data to ensure it is correct and send to me or let me know it is corrected.  I will validate the test data.  We will keep the subject data in case later we decide to use it but for now we will not operate on it.

**Comment by chenshenlv** [comment]
Got it will fix it tonight

**Comment by tarce** [comment]
I will close this issue since it looks like its been resolved.  Please double check during the experiment on Monday after the first subject that data is being correctly stored.
